exo_list_builder.exo_entity_list.*:
  type: config_entity
  label: 'eXo Entity List config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    key:
      type: string
      label: 'Query Key'
    target_entity_type:
      type: string
      label: 'Entity Type'
    target_bundles_include:
      type: sequence
      label: Include Bundles
      sequence:
        type: string
    target_bundles_exclude:
      type: sequence
      label: Exclude Bundles
      sequence:
        type: string
    override:
      type: boolean
      label: Override List Builder
    format:
      type: string
      label: Format
    url:
      type: string
      label: URL
    limit:
      type: integer
      label: 'Limit'
    limit_options:
      type: sequence
      label: 'Limit Options'
      sequence:
        type: integer
    offset:
      type: integer
      label: 'Offset'
    actions:
      type: sequence
      label: Actions
      sequence:
        type: mapping
        mapping:
          settings:
            type: ignore
            label: 'Settings'
    sorts:
      type: sequence
      label: Sorts
      sequence:
        type: mapping
        mapping:
          settings:
            type: ignore
            label: 'Settings'
    sort:
      type: string
      label: Default sort field
    references:
      type: sequence
      label: 'References'
      sequence:
        type: mapping
        mapping:
          status:
            type: boolean
            label: 'Status'
          fields:
            type: sequence
            label: 'Fields'
    fields:
      type: sequence
      label: Fields
      sequence:
        type: mapping
        mapping:
          display_label:
            type: string
            label: 'Display Label'
          view:
            type: mapping
            mapping:
              type:
                type: string
                label: 'Element Type'
              settings:
                type: ignore
                label: 'Settings'
              toggle:
                type: boolean
                label: 'Toggleable'
              show:
                type: boolean
                label: 'Show by default'
              wrapper:
                type: string
                label: 'Wrapper'
              align:
                type: string
                label: 'Align'
              size:
                type: string
                label: 'Size'
              group_by:
                type: boolean
                label: 'Group By'
              group_by_sort:
                type: string
                label: 'Group By Sort'
              sort:
                type: string
                label: 'Sort'
              sort_asc_label:
                type: string
                label: 'Sort Ascending Label'
              sort_desc_label:
                type: string
                label: 'Sort Descending Label'
              sort_natsort:
                type: boolean
                label: 'Natural Sort'
              sort_secondary:
                type: boolean
                label: 'Secondary Sort'
          filter:
            type: mapping
            mapping:
              type:
                type: string
                label: 'Filter Type'
              settings:
                type: ignore
                label: 'Settings'
          weight:
            type: integer
            label: 'Weight'
    settings:
      type: ignore
      label: 'Settings'
    weight:
      type: integer
      label: 'Weight'
