<?php

/**
 * Implements hook_install().
 */
function exo_list_builder_commerce_install() {
  $config = \Drupal::configFactory()->getEditable('views.view.commerce_promotions');
  if ($config) {
    $config->set('status', FALSE)->save(TRUE);
  }
}

/**
 * Implements hook_uninstall().
 */
function exo_list_builder_commerce_uninstall() {
  $config = \Drupal::configFactory()->getEditable('views.view.commerce_promotions');
  if ($config) {
    $config->set('status', TRUE)->save(TRUE);
  }
}
