<?php

/**
 * @file
 * Contains exo_list_builder_webform.module.
 */

/**
 * Implements hook_entity_type_alter().
 */
function exo_list_builder_webform_entity_type_alter(array &$entity_types) {
  foreach ($entity_types as $entity_type_id => $entity_type) {
    if ($entity_type_id === 'webform') {
      $entity_type->setHandlerClass('exo_list_builder', 'Drupal\exo_list_builder_webform\ExoListBuilderConfigWebform');
    }
  }
}
