<?php

/**
 * @file
 * Contains exo_linkit.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function exo_linkit_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the exo_linkit module.
    case 'help.page.exo_linkit':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Adds a widget to replace the core link field with linkit field.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_library_info_build().
 */
function exo_linkit_library_info_alter(&$libraries, $extension) {
  if ($extension === 'linkit') {
    unset($libraries['linkit.autocomplete']['js']['js/linkit.autocomplete.js']);
    $path = '/' . \Drupal::service('extension.list.module')->getPath('exo_linkit');
    $libraries['linkit.autocomplete']['js'][$path . '/js/exo.linkit.autocomplete.js'] = ['minified' => TRUE];
  }
}
