<?php

/**
 * @file
 * Contains exo_oembed.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use GuzzleHttp\Exception\RequestException;

/**
 * Implements hook_help().
 */
function exo_oembed_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the exo_oembed module.
    case 'help.page.exo_oembed':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Provides enhancments to oEmbed.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_oembed_oembed_resource_data_alter().
 *
 * This hook will retrieve the highest quality thumbnail from youtube/vimeo.
 *
 * Requires a core path to work.
 *
 * @see https://www.drupal.org/files/issues/2024-03-12/3042423.patch
 */
function exo_oembed_oembed_resource_data_alter(array &$data, $url) {
  $client = \Drupal::httpClient();
  if (strpos($url, 'youtube.com/oembed') !== FALSE) {
    $thumbnailUrl = str_replace('hqdefault', 'maxresdefault', $data['thumbnail_url']);
    try {
      $client->get($thumbnailUrl);
    } catch (RequestException $e) {
      $thumbnailUrl = str_replace('hqdefault', 'sddefault', $data['thumbnail_url']);
      try {
        $client->get($thumbnailUrl);
      } catch (RequestException $e) {
        $thumbnailUrl = $data['thumbnail_url'];
      }
    }
    $data['thumbnail_url'] = $thumbnailUrl;
  }
  elseif (strpos($url, 'vimeo.com/api/oembed') !== FALSE) {
    $thumbnailUrl = str_replace('295x166', '1280', $data['thumbnail_url']);
    try {
      $client->get($thumbnailUrl);
      $data['thumbnail_width'] = '1280';
      $data['thumbnail_height'] = '720';
    } catch (RequestException $e) {
      $thumbnailUrl = str_replace('295x166', '960', $data['thumbnail_url']);
      try {
        $client->get($thumbnailUrl);
        $data['thumbnail_width'] = '960';
        $data['thumbnail_height'] = '540';
      } catch (RequestException $e) {
        $thumbnailUrl = $data['thumbnail_url'];
      }
    }

    $data['thumbnail_url'] = $thumbnailUrl;
  }
}
