name: 'eXo Config'
type: module
description: 'Provides base configuration for Config Split and Config Readonly and ties the two together in a best-practices workflow.'
package: 'eXo'
core_version_requirement: ^10 || ^11
version: 2.0.27
dependencies:
  - config_split:config_split
  - config_readonly:config_readonly
  - config_ignore:config_ignore
