<?php

/**
 * @file
 * Contains exo_menu_component.module.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\exo_menu_component\MenuComponentOperations;
use Drupal\menu_link_content\MenuLinkContentInterface;

/**
 * Implements hook_help().
 */
function exo_menu_component_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the exo_menu_component module.
    case 'help.page.exo_menu_component':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Provides in-menu entity support.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function exo_menu_component_theme() {
  $theme = [];
  $theme['exo_menu_component'] = [
    'render element' => 'elements',
    'file' => 'exo_menu_component.page.inc',
  ];
  $theme['exo_menu_component_add_list'] = [
    'variables' => ['menu' => NULL, 'content' => NULL],
    'file' => 'exo_menu_component.page.inc',
  ];
  return $theme;
}

/**
 * Implements hook_theme_suggestions_HOOK().
 */
function exo_menu_component_theme_suggestions_exo_menu_component(array $variables) {
  $suggestions = [];
  $entity = $variables['elements']['#exo_menu_component'];
  $sanitized_view_mode = strtr($variables['elements']['#view_mode'], '.', '_');
  $suggestions[] = 'exo_menu_component__' . $sanitized_view_mode;
  $suggestions[] = 'exo_menu_component__' . $entity->bundle();
  $suggestions[] = 'exo_menu_component__' . $entity->bundle() . '__' . $sanitized_view_mode;
  $suggestions[] = 'exo_menu_component__' . $entity->id();
  $suggestions[] = 'exo_menu_component__' . $entity->id() . '__' . $sanitized_view_mode;
  return $suggestions;
}

/**
 * Implements hook_preprocess_HOOK().
 */
function exo_menu_component_preprocess_exo_menu(&$variables) {
  /** @var \Drupal\exo_menu_component\MenuComponentOperations $component_operations */
  $component_operations = \Drupal::classResolver(MenuComponentOperations::class);
  $component_operations->replaceComponents($variables['items']);
}

/**
 * Implements hook_preprocess_HOOK().
 */
function exo_menu_component_preprocess_exo_menu_levels(&$variables) {
  /** @var \Drupal\exo_menu_component\MenuComponentOperations $component_operations */
  $component_operations = \Drupal::classResolver(MenuComponentOperations::class);
  foreach ($variables['levels'] as &$value) {
    $component_operations->replaceComponents($value['items']);
  }
}

/**
 * Implements hook_form_BASE_FORM_ID_alter().
 */
function exo_menu_component_form_menu_link_content_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  /** @var \Drupal\exo_menu_component\MenuComponentOperations $component_operations */
  $component_operations = \Drupal::classResolver(MenuComponentOperations::class);
  $component_operations->handleForm($form, $form_state);
}

/**
 * Implements hook_ENTITY_TYPE_delete().
 */
function exo_menu_component_menu_link_content_delete(MenuLinkContentInterface $menu_link) {
  $menu_link_options = $menu_link->link->first()->options;
  if (isset($menu_link_options['attributes']['data-exo-menu-component'])) {
    $exo_menu_component = \Drupal::entityTypeManager()->getStorage('exo_menu_component')->load($menu_link_options['attributes']['data-exo-menu-component']);
    $exo_menu_component->delete();
  }
}
