name: 'eXo Site Settings: Domain'
type: module
description: 'Provides domain access support to site settings.'
package: 'eXo'
core_version_requirement: ^10 || ^11
version: 2.0.27
dependencies:
  - domain_access:domain_access
