<?php

/**
 * @file
 * Contains exo_video.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function exo_video_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the exo_video module.
    case 'help.page.exo_video':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Provides enhanced video display formatters.') . '</p>';
      return $output;

    default:
  }
}
