<?php

/**
 * @file
 * Contains exo_fixed.module.
 */

use Drupal\Component\Utility\Html;
use Drupal\Core\Template\Attribute;

/**
 * Implements hook_element_info_alter().
 */
function exo_fixed_element_info_alter(&$type) {
  if (isset($type['page'])) {
    $type['page']['#pre_render'][] = ['\Drupal\exo_fixed\ExoFixedPreRender', 'preRender'];
  }
}

/**
 * Make element fixed.
 *
 * @param array $element
 *   The element to make into a fixed element.
 * @param string $id
 *   A unique id.
 * @param string $type
 *   Either 'always', 'scroll' or 'sticky'
 *
 * @param array $element
 */
function exo_fixed_element(array &$element, $id, $type = 'always') {
  $html_id = Html::getUniqueId('exo-fixed-' . $id);
  $element['#theme_wrappers']['exo_fixed_wrapper'] = ['#weight' => -1000];
  $element['#exo_wrapper_attributes']['id'] = $html_id;
  $element['#exo_wrapper_attributes']['class'][] = 'exo-fixed';
  $element['#exo_wrapper_attributes']['class'][] = 'exo-fixed-' . Html::getClass($id);
  $element['#exo_wrapper_attributes']['class'][] = 'exo-fixed-' . Html::getClass($type);
  $element['#attributes']['class'][] = 'exo-fixed-element';
  $element['#attached']['library'][] = 'exo_fixed/base';
  $element['#attached']['drupalSettings']['exoFixed']['elements'][$id] = [
    'type' => $type,
    'selector' => '#' . $html_id,
  ];
}

/**
 * Implements hook_theme().
 */
function exo_fixed_theme($existing, $type, $theme, $path) {
  return [
    'exo_fixed_wrapper' => [
      'variables' => [
        'children' => NULL,
        'exo_wrapper_attributes' => [],
      ],
    ],
  ];
}

/**
 * Preprocess exo_fixed_wrapper.
 */
function template_preprocess_exo_fixed_wrapper(&$variables) {
  $variables['exo_wrapper_attributes'] = new Attribute($variables['exo_wrapper_attributes']);
}
