<?php

/**
 * @file
 * Contains exo_entity_browser.module.
 */

/**
 * Implements hook_theme().
 */
function exo_entity_browser_theme($existing, $type, $theme, $path) {
  $entity_browser_path = drupal_get_path('module', 'entity_browser') . '/templates';
  return [
    // Render only the content area for entity browser modals.
    'html__entity_browser__exo_modal' => [
      'template' => 'html--entity-browser--iframe',
      'render element' => 'html',
      'path' => $entity_browser_path,
      'preprocess functions' => ['template_preprocess_html'],
    ],
    'page__entity_browser__exo_modal' => [
      'template' => 'page--entity-browser--iframe',
      'render element' => 'html',
      'path' => $entity_browser_path,
      'preprocess functions' => ['template_preprocess_page'],
    ],
    'html__entity_browser__exo_iframe' => [
      'template' => 'html--entity-browser--iframe',
      'render element' => 'html',
      'path' => $entity_browser_path,
      'preprocess functions' => ['template_preprocess_html'],
    ],
    'page__entity_browser__exo_iframe' => [
      'template' => 'page--entity-browser--iframe',
      'render element' => 'html',
      'path' => $entity_browser_path,
      'preprocess functions' => ['template_preprocess_page'],
    ],
  ];
}

/**
 * Implements hook_preprocess_html__entity_browser__exo_modal().
 *
 * Tries to figure out where messages block lives and display it separately.
 */
function exo_entity_browser_preprocess_html__entity_browser__exo_modal(&$variables) {
  $variables['html_attributes']->addClass(['exo-modal-view', 'exo-reset']);
}

/**
 * Implements hook_preprocess_page__entity_browser__exo_modal().
 *
 * Tries to figure out where messages block lives and display it separately.
 */
function exo_modal_preprocess_page__entity_browser__exo_modal(&$variables) {
  entity_browser_preprocess_page__entity_browser__iframe($variables);
  $variables['#attached']['library'][] = 'exo_entity_browser/view';
}

/**
 * Implements hook_preprocess_html__entity_browser__exo_iframe().
 *
 * Tries to figure out where messages block lives and display it separately.
 */
function exo_entity_browser_preprocess_html__entity_browser__exo_iframe(&$variables) {
  exo_entity_browser_preprocess_html__entity_browser__exo_modal($variables);
}

/**
 * Implements hook_preprocess_page__entity_browser__exo_iframe().
 *
 * Tries to figure out where messages block lives and display it separately.
 */
function exo_modal_preprocess_page__entity_browser__exo_iframe(&$variables) {
  exo_modal_preprocess_page__entity_browser__exo_modal($variables);
}

/**
 * Implements hook_library_info_alter().
 */
function exo_entity_browser_library_info_alter(&$libraries, $extension) {
  if ($extension == 'entity_embed') {
    $libraries['drupal.entity_embed.dialog']['dependencies'][] = 'exo_entity_browser/view';
  }
}
